require("basic")
require("keybindings")
require("plugins")
require("colorscheme")

require("plugin-configs.formatter")
require("plugin-configs.nvim-tree")
require("plugin-configs.bufferline")
require("plugin-configs.lualine")
require("plugin-configs.fzf")
require("plugin-configs.treesitter")
--require("plugin-configs.indent-blankline")
--require("plugin-configs.nerdcommenter")
